### PR TITLE
fix: refactor excluded files in ember package entites

### LINKED ISSUE #813: lint config files are being changed from js to ts
In migrating hue libraries, for example, hue-web-button, lint config files, such as .eslintrc.js, .rehearsal-eslintrc.js, and .template-lint.js are being converted to ts files. TS errors and lint errors are being produced for these files, and lint errors for other source files become inaccurate because of this.

### PR DESCRIPTION
**Pull request by wondersloth**
Fixes #813, #761

### Fixed
* `.rehearsal-eslint.js` excludes in all packages
* `.eslintrc.js` was not being excluded in ember package entities. Refacotred to pass package excludes to ember entities.
*  Adds ember-template-lint `.template-lintrc.js` to common ember excludes.

### Changed
* Refactored excludes to stand alone files in packages
* Ember excludes extend from `migration-graph-shared` default excludes.
* Add tests for Packages validating excluded files and directories.

### CODE REVIEW

**Comment by brendaHuang** [comment]
I tried hue-web-button again, .template-lintrc.js is being changed to .template-lintrc.ts.

**Review by egorio — APPROVED** [review]

File: packages/migration-graph-ember/src/utils/excludes.ts [hunk 1]
```diff
@@ -0,0 +1,16 @@
+import { getExcludePatterns } from '@rehearsal/migration-graph-shared';
+
+const EMBER_FILES = [
+  '.ember-cli.js',
+  '.template-lint.js', // ember-template-lint
```
Comment (wondersloth) [inline packages/migration-graph-ember/src/utils/excludes.ts:5]: This should be `.template-lintrc.js`

**Comment by wondersloth** [comment]
> I tried hue-web-button again, .template-lintrc.js is being changed to .template-lintrc.ts.

Just pushed a fix for this filename.
