### PR TITLE
refactor: move fix into a worker

### LINKED ISSUE #441: Handle SIGINT (ctrl + c) in migrate CLI

### LINKED ISSUE #1079: bug: unable to kill process when running rehearsal `CTRL+C` does not kill fix
When running rehearsal in long running **fix**'s the process cannot be killed with `CTRL+C`

Only able to kill process by finding process id and performing `kill -9 <PID>`

### PR DESCRIPTION
**Pull request by lynchbomb**
Fixes #1079 
Fixes #441 

This PR:

- finally closes out the blocking thread issue with `fix` as SIGINT is now respected killing the worker thread
- minor change to the reporter package as `basePath` in this package was super confusing (its looking for the directory to save the report to) as such was changed to `reportOutDir`
- minor change to `getReportSummary()` helper 

https://github.com/rehearsal-js/rehearsal-js/assets/10506014/396ee783-1647-4353-bdb2-86b38f904e6f

### CODE REVIEW

**Review by egorio — APPROVED** [review]

File: packages/cli/src/commands/fix/tasks/convert-task.ts [hunk 1]
```diff
@@ -29,37 +33,76 @@ export function convertTask(
...
-          packageDir: packageDir,
-          filesToMigrate: ctx.orderedFiles,
-          reporter,
-          task,
-          ignore,
-        };
+        const migratedFiles: string[] = [];
 
-        const migratedFiles = [];
+        if (process.env['TEST'] === 'true' || process.env['WORKER'] === 'false') {
```
Comment (egorio) [inline packages/cli/src/commands/fix/tasks/convert-task.ts:50]: `TEST` - is so broad :)
